# 1. Variables and Data Types

In [1]:
# Integer variable
age = 25
print("My age is:", age)
print(type(age))

# Float (or numeric/real number) variable
temperature = 98.6
print("The temperature is:", temperature)
print(type(temperature))

# String (or text) variable
name = "John Doe"
print("My name is:", name)
print(type(name))

# Boolean (or Logical) variable
is_student = True
print("Am I a student?", is_student)
print(type(is_student))

# List variable
fruits = ["apple", "banana", "orange"]
print("My favorite fruits are:", fruits)
print(type(fruits))

# Dictionary variable
person = {"name": "Alice", "age": 30, "city": "New York"}
print("Person details:", person)
print(type(person))

# Tuple variable
coordinates = (40.7128, -74.0060)
print("Coordinates:", coordinates)
print(type(coordinates))


My age is: 25
<class 'int'>
The temperature is: 98.6
<class 'float'>
My name is: John Doe
<class 'str'>
Am I a student? True
<class 'bool'>
My favorite fruits are: ['apple', 'banana', 'orange']
<class 'list'>
Person details: {'name': 'Alice', 'age': 30, 'city': 'New York'}
<class 'dict'>
Coordinates: (40.7128, -74.006)
<class 'tuple'>


1. age: It is an **integer** variable that represents a person's age. In the example, it is assigned the value 25.

2. temperature: It is a **float** variable that represents a temperature measurement. In the example, it is assigned the value 98.6.

3. name: It is a **string** variable that stores a person's name. In the example, it is assigned the value "John Doe".

4. is_student: It is a **boolean** variable that stores a true/false value indicating whether a person is a student or not. In the example, it is assigned the value True.

5. fruits: It is a **list** variable that stores a collection of fruits. In the example, it is assigned the value ["apple", "banana", "orange"]. Lists are ordered collections that can hold different types of elements.

6. person: It is a **dictionary** variable that stores information about a person. In the example, it is assigned the value {"name": "Alice", "age": 30, "city": "New York"}. Dictionaries are unordered collections that store key-value pairs.

7. coordinates: It is a **tuple** variable that represents a pair of coordinates (latitude and longitude). In the example, it is assigned the value (40.7128, -74.0060). Tuples are immutable sequences typically used to store related values together.

# 2. Control Flow

In [2]:
# If-else statement
age = 18
if age >= 18:
    print("You are eligible to vote.")
else:
    print("You are not eligible to vote yet.")

# Elif statement
grade = 85
if grade >= 90:
    print("Your grade is A.")
elif grade >= 80:
    print("Your grade is B.")
elif grade >= 70:
    print("Your grade is C.")
else:
    print("Your grade is below C.")

# For loop
fruits = ["apples", "bananas", "oranges"]
for fruit in fruits:
    print("I like", fruit)

# While loop
count = 1
while count <= 5:
    print("Count:", count)
    count += 1

# Break statement
for num in range(1, 10):
    if num == 5:
        break
    print("Number:", num)

# Continue statement
for num in range(1, 6):
    if num == 3:
        continue
    print("Number:", num)
     

You are eligible to vote.
Your grade is B.
I like apples
I like bananas
I like oranges
Count: 1
Count: 2
Count: 3
Count: 4
Count: 5
Number: 1
Number: 2
Number: 3
Number: 4
Number: 1
Number: 2
Number: 4
Number: 5


In this script, we have examples of different control flow statements:

1. **if-else** statement: It checks if a given condition is true and executes the corresponding block of code. In the example, it checks the age variable and determines whether the person is eligible to vote.

2. **elif** statement: It allows checking multiple conditions using "else if" clauses. In the example, it determines the grade based on the grade variable.

3. **for** loop: It iterates over a sequence (in this case, a list of fruits) and performs a set of actions for each element.

4. **while** loop: It repeatedly executes a block of code as long as a condition is true. In the example, it prints the count from 1 to 5.

5. **break** statement: It terminates the execution of a loop prematurely. In the example, the loop stops when num equals 5.

6. **continue** statement: It skips the rest of the loop iteration and moves to the next iteration. In the example, it skips printing the number 3.

# 3. Operators

In [3]:
## Arithmetic Operators

x = 17
y = 3

print (x+y)
print (x-y)
print (x*y)
print (x/y)
print (x%y)
print (x//y)
print (x**y)

20
14
51
5.666666666666667
2
5
4913


In [4]:
## Comparison Operators

x = 17
y = 3

print ("x less than y :", x<y)
print ("x less than or equal to y :",x<=y)
print ("x equals y :",x==y)
print ("x greater than y :",x>y)
print ("x greater than or equal to y :",x>=y)
print ("x not equals y :",x!=y)

x less than y : False
x less than or equal to y : False
x equals y : False
x greater than y : True
x greater than or equal to y : True
x not equals y : True


In [5]:
## Logical Operators

x = True
y = False
z = True

print ("True or False :", x or y)
print ("True and False :",x and y)
print ("True and True :",x and z)
print ("not True :",not x)

True or False : True
True and False : False
True and True : True
not True : False


In [6]:
## Assignment Operators

x = 17
y = 3

x+=y
print(x)
x-=y
print(x)
x*=y
print(x)
x&=y
print(x)
x|=y
print(x)


20
17
51
3
3


# 4. Modules

When you install python you get the Python interpreter, its built-in types and function and python standard library. By using import module we can use it's function in our program.

References: 
The Python Language Reference: http://docs.python.org/2/reference/index.html </br>
            
The Python Standard Library: http://docs.python.org/2/library/



In [7]:
# To use a module in a Python program it first has to be imported. A module can be imported using the import statement. For example, to import the module math, which contains many standard mathematical functions, we can do:

import math
math.sqrt(36)

#help(math.sqrt)
#dir(math) # To view the function with math module, we can use dir(math)

6.0

# 5. Function

In [8]:
# Function without parameters
def greet():
    print("Hello, there!")

# Function with parameters
def add_numbers(a, b):
    sum = a + b
    return sum

# Function with default parameter value
def multiply_numbers(a, b=2):
    product = a * b
    return product

# Function with variable number of arguments
def calculate_average(*numbers):
    total = sum(numbers)
    average = total / len(numbers)
    return average

# Calling functions
greet()  # Output: Hello, there!

result = add_numbers(3, 5)
print("Sum:", result)  # Output: Sum: 8

result = multiply_numbers(4)
print("Product:", result)  # Output: Product: 8

result = calculate_average(2, 4, 6, 8)
print("Average:", result)  # Output: Average: 5.0

Hello, there!
Sum: 8
Product: 8
Average: 5.0


In this script, we have examples of different function concepts:

1. **Function without parameters**: The greet() function does not take any parameters and simply prints a greeting message.

2. **Function with parameters**: The add_numbers(a, b) function takes two parameters a and b, adds them together, and returns the sum.

3. **Function with default parameter value**: The multiply_numbers(a, b=2) function takes two parameters a and b, multiplies them together, and returns the product. If the b parameter is not provided, it defaults to 2.

4. **Function with variable number of arguments**: The calculate_average(numbers) function uses the numbers syntax to accept any number of arguments. It calculates the average of all the numbers and returns the result.

# 6. Input & Output Operations

In [9]:
import time

# Input from the user
print("CHATBOT:")
print("Hello! I am a bot designed to ask you a few questions.")
time.sleep(2)
print("... but before we begin, I've forgotten my own name.")
print("")

time.sleep(2)
print("CHATBOT:")
bot_name = input("Q: Can you remind me what my name is? ")
bot_name = bot_name.upper()
print("")
time.sleep(1)
print(bot_name + ":")
print("Of course! That's right! Thank you for reminding me!")
time.sleep(2)

print("... okay, now let's get to those questions!")
print("")
time.sleep(2)

# Input from the user
print(bot_name + ":")
name = input("Q: What is your name? ")
print("")
time.sleep(1)
print(bot_name + ":")
print("Hello, " + name + ".")
print("It's nice to meet you!")
print("")
time.sleep(2)

# Reading numeric input
print(bot_name + ":")
age = int(input("Q: " + name + ", how old are you? "))
print("")
time.sleep(1)
print(bot_name + ":")
print("Thank you for the information, " + name + ".")
time.sleep(1)
print("... " + str(age) + " years old is a wonderful age to be!")
print("")
time.sleep(3)

# Output formatting
print(bot_name + ":")
height = float(input("Q: How tall are you (in cm)? "))
print("")
time.sleep(1)
print(bot_name + ":")
print("Thank you for that. One more question...")
print("")
time.sleep(2)
print(bot_name + ":")
weight = float(input("Q: If you don't mind, how much do you weigh (in kg)? "))
print("")
time.sleep(2)
print(bot_name + ":")
print(f"Now I know that your height is {height:.0f} cm and your weight is {weight:.0f} kg.")
time.sleep(2)
print("... please give me a few seconds to calculate your BMI.")
print("")

# Loop to print dots
for _ in range(6):
    print(".", end="", flush=True)  # Print dot without a newline
    time.sleep(1)  # Delay of 1 second between dots

print("")
print("")
print(bot_name + ":")
print("I've calculated that you have the perfect ratio of height and weight!")
time.sleep(2)
print("... Thank you for answering my questions! Have a nice day, " + name + "!")
print("")

CHATBOT:
Hello! I am a bot designed to ask you a few questions.
... but before we begin, I've forgotten my own name.

CHATBOT:


Q: Can you remind me what my name is?  Chat



CHAT:
Of course! That's right! Thank you for reminding me!
... okay, now let's get to those questions!

CHAT:


Q: What is your name?  Sanju



CHAT:
Hello, Sanju.
It's nice to meet you!

CHAT:


Q: Sanju, how old are you?  20



CHAT:
Thank you for the information, Sanju.
... 20 years old is a wonderful age to be!

CHAT:


Q: How tall are you (in cm)?  100



CHAT:
Thank you for that. One more question...

CHAT:


Q: If you don't mind, how much do you weigh (in kg)?  100



CHAT:
Now I know that your height is 100 cm and your weight is 100 kg.
... please give me a few seconds to calculate your BMI.

......

CHAT:
I've calculated that you have the perfect ratio of height and weight!
... Thank you for answering my questions! Have a nice day, Sanju!



In [10]:
# Writing to a file
file_path = "output.txt"
with open(file_path, "w") as file:
    file.write("\nThis is some text.\n")  # The \n escape sequence in the first string inserts a new line
    file.write("This is another line.")  # So this second line will appear on a new line

# Reading from a file
with open(file_path, "r") as file:
    content = file.read()
    print("\nContent of the file:\n", content)
     


Content of the file:
 
This is some text.
This is another line.


1. Input from the user:
. The input() function is used to prompt the user to enter their name.
. The entered name is stored in the name variable.
. The print() function is used to display a greeting message, including the entered name.

2. Reading numeric input:
. The input() function is used to prompt the user to enter their age.
. The entered value is treated as a string.
. The int() function is used to convert the entered string to an integer and store it in the age variable.
. Two print() statements are used to display an empty line and the user's age.

3. Output formatting:
. The height and weight variables are defined with float values representing height in meters and weight in kilograms.
. Two print() statements are used to display an empty line and formatted output for height and weight.
The format() method is used to format the values with specific decimal places.

4. Writing to a file:
. The file_path variable is set to "output.txt", specifying the name of the file to be written.
. The open() function is used to open the file in write mode ("w").
. The with statement ensures that the file is properly closed after writing.
. The write() method is used to write two strings to the file. The first string starts with a newline (\n) escape sequence, which inserts a new line in the file.

5. Reading from a file:
. The with statement is used to open the file in read mode ("r").
. The file.read() method reads the content of the file and stores it in the content variable.
. A print() statement is used to display an empty line, followed by the content of the file.

# 7. Lists & Indexing

In [11]:
# Creating a list
fruits = ["apple", "banana", "orange", "grape", "kiwi"]
print("Fruits:", fruits)

# Accessing elements by index
print("First fruit:", fruits[0])
print("Third fruit:", fruits[2])
print("Last fruit:", fruits[-1])

# Modifying elements by index
fruits[1] = "pear"
print("Modified fruits:", fruits)

# Slicing a list
subset = fruits[1:4]
print("Subset:", subset)

# Adding elements to a list
fruits.append("mango")
fruits.insert(2, "pineapple")
print("Updated fruits:", fruits)

# Removing elements from a list
removed_fruit = fruits.pop(3)
print("Removed fruit:", removed_fruit)
print("Updated fruits:", fruits)

# Length of a list
num_fruits = len(fruits)
print("Number of fruits:", num_fruits)

# Checking if an element is in a list
if "kiwi" in fruits:
    print("Kiwi is in the list.")
else:
    print("Kiwi is not in the list.")

Fruits: ['apple', 'banana', 'orange', 'grape', 'kiwi']
First fruit: apple
Third fruit: orange
Last fruit: kiwi
Modified fruits: ['apple', 'pear', 'orange', 'grape', 'kiwi']
Subset: ['pear', 'orange', 'grape']
Updated fruits: ['apple', 'pear', 'pineapple', 'orange', 'grape', 'kiwi', 'mango']
Removed fruit: orange
Updated fruits: ['apple', 'pear', 'pineapple', 'grape', 'kiwi', 'mango']
Number of fruits: 6
Kiwi is in the list.


In this script, we have examples of lists and indexing:

1. Creating a list: The fruits list is created with five initial elements.

2. Accessing elements by index: Elements of the list can be accessed using square brackets [] with the index position. Indexing starts from 0, and negative indices count from the end of the list.

3. Modifying elements by index: Elements in the list can be modified by assigning a new value to a specific index.

4. Slicing a list: A subset of elements can be extracted from the list using the slicing technique. It allows specifying a range of indices to retrieve a portion of the list.

5. Adding elements to a list: Elements can be added to a list using the append() method to add at the end or the insert() method to insert at a specific index.

6. Removing elements from a list: Elements can be removed from a list using the pop() method, which removes and returns the element at a specific index.

7. Length of a list: The len() function is used to determine the number of elements in a list.

8. Checking if an element is in a list: The in keyword is used to check if a particular element exists in the list.

# 8. Error Handling 

In [12]:
# Handling a specific exception
try:
    num = int(input("Enter a number: "))
    result = 10 / num
    print("Result:", result)
except ValueError:
    print("Invalid input. Please enter a valid number.")
except ZeroDivisionError:
    print("Cannot divide by zero.")

Enter a number:  7


Result: 1.4285714285714286


In [13]:
# Handling multiple exceptions
try:
    index = int(input("Enter an index: "))
    fruit = ["apple", "banana", "orange", "blueberry", "pineapple", "dragonfruit", "lime", "grape"]
    print("Selected fruit:", fruit[index])
except (ValueError, IndexError):
    print("Invalid input or index out of range.")
     

Enter an index:  6


Selected fruit: lime


In [14]:
# Handling any exception
try:
    file = open("nonexistent.txt", "r")
    content = file.read()
    file.close()
    print("File content:", content)
except Exception as e:
    print("An error occurred:", str(e))

An error occurred: [Errno 2] No such file or directory: 'nonexistent.txt'


In this script, we have examples of error handling:

1. Handling a specific exception: The try block is used to contain the code that may raise an exception. If a ValueError or ZeroDivisionError occurs, the corresponding except block is executed, and an appropriate error message is displayed.

2. Handling multiple exceptions: The try block contains code that may raise a ValueError or an IndexError. If either exception occurs, the common except block is executed, and an error message is displayed.

3. Handling any exception: The try block contains code that tries to open a file that does not exist. Since this can potentially raise various types of exceptions, the except block uses the generic Exception class to catch any exception. The error message is displayed using the str(e) representation of the exception object.

# 9. Example 1

Create a rock paper scissor game where you will provide the input and computer will choose randomly. Check who wins the

game you or the computer.

Hint: 
1. Create a list. list = ["rock","paper","scissors"]
2. Computer choice. 
    - import random
    - random.choice(list) # This gives random choice from the above list for the computer
3. Use input to input your choice from keyboard
4. Use if elif else statement to compare computer choice and your choice and see who wins

# 10. Class

A class is defined almost like a function, but using the class keyword, and the class definition usually contains a number of class method definitions (a function in a class).

Each class method should have an argument self as its first argument. This object is a self-reference.

Some class method names have special meaning, for example:

__init__: The name of the method that is invoked when the object is first created. </br>
__str__ : A method that is invoked when a simple string representation of the class is needed, as for example when printed.
There are many more, see http://docs.python.org/2/reference/datamodel.html#special-method-names


In [15]:
class MyClass:
    def num(self):
        return 10
f = MyClass()
print(f.num())

10


In [16]:
class Point:
    """
    Simple class for representing a point in a Cartesian coordinate system.
    """
    
    def __init__(self, x, y):
        """
        Create a new Point at x, y.
        """
        self.x = x
        self.y = y
        
    def translate(self, dx, dy):
        """
        Translate the point by dx and dy in the x and y direction.
        """
        self.x += dx
        self.y += dy
        
    def __str__(self):
        return("Point at [%f, %f]" % (self.x, self.y))

    
p1 = Point(0,1) # this will invoke the __init__ method in the Point class

print(p1)         # this will invoke the __str__ method

Point at [0.000000, 1.000000]


# 11. Example 2

Create a class to manage your bank account. This class should have following functiality. deposit, withdraw and class itself should return the current balance of the account.

Hint:

class BankAccount:</br>

    def __init__(self):</br>
        # add your code here

    def deposit(self):
        # add your code here

    def withdraw(self):
        #add your code here

